## 1. Import Numpy as np and show its version

In [2]:
import numpy as np
print(f"Su versión de Numpy es: {np.__version__}.")

Su versión de Numpy es: 1.23.4.


## 2. How to create a 1D array?

Difficutly level: L1 <br>
<br>
Desired output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. How to create a boolean array?

Difficulty Level: L1 <br>
<br>
Q. Create a 3×3 numpy array of all True’s

In [15]:
arr = np.full((3,3), True)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [27]:
## Metodo alternativo
arr = np.ones((3,3), dtype = bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## 4. How to extract items that satisfy a given condition from 1D array?

Difficulty Level: L1 <br>
<br>
Q. Extract all odd numbers from arr <br>
- Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
<br>
- Output: array([1, 3, 5, 7, 9])

In [38]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]


array([1, 3, 5, 7, 9])

## 5. How to replace items that satisfy a condition with another value in numpy array?

Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

- Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Desired Output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [41]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. How to replace items that satisfy a condition without affecting the original array?

Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

- Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Desired output: <br>
        Out<br>
        array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])<br>
        arr<br>
        array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])<br>

In [48]:
## Metodo mío

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = arr.copy()
arr2[arr2 % 2 == 1] = -1
print(arr2)
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [53]:
## Metodo de la pagina (ADECUADO)

arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)       # Metodo where
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


## 7. How to reshape an array?

Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

- Input: <br>
        array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Desidered output: <br>
        array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])


In [70]:
## Mi solución
arr = np.arange(10)
arr.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
## Solución de la pagina
arr = np.arange(10)
arr.reshape(2,-1)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. How to stack two arrays vertically?

Difficulty Level: L2

Q. Stack arrays a and b vertically

- Input:<br>
    - a = np.arange(10).reshape(2,-1) <br>
    - b = np.repeat(1, 10).reshape(2,-1)<br>

- Desired output: <br>
<p>
([[0, 1, 2, 3, 4],<br>
[5, 6, 7, 8, 9],<br>
[1, 1, 1, 1, 1],<br>
[1, 1, 1, 1, 1]])
</p>

In [100]:
## Metodo mío

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.vstack([a,b])
c


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [101]:
## Metodo pagína 1

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate([a,b])
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [102]:
## Metodo pagína 2

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.r_[a, b]
c


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9. How to stack two arrays horizontally?